sample_app/config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    resources :microposts
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => "pages#home"
  

end

sample_app/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

sample_app/app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <div class="microposts" summary="User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </div>
  <%= will_paginate @feed_items %>
<% end %>

sample_app/app/views/shared/_feed_item.html.erb
<div class="micropost_item">
  <div class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </div>
  <% user = feed_item.user rescue User.find(feed_item.user_id) %>
  <% if current_user?(user) %>
  <div class="delete">
    <%= link_to "delete", feed_item, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => feed_item.content %>
  </div>
  <% end %>
  <div class="micropost">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= wrap(feed_item.content) %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </div>
</div>

sample_app/app/views/shared/_home_not_signed_in.html.erb
  <h1>Sample App</h1>

  <p>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </p>

  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

sample_app/app/views/shared/_home_signed_in.html.erb
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
  </table>

sample_app/app/views/shared/_micropost_form.html.erb
<%= javascript_include_tag 'micropost_form_counter' %>
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content, :onkeyup    => 'javascript:changeCounter();', 
                              :onkeydown  => 'javascript:changeCounter();',
                              :onkeypress => 'javascript:changeCounter();' %>
  </div>
  <div class="counter_text">
    Characters left:
  </div>
  <span id="counter" class="counter_norm">
    <%= @micropost.class.validators_on(:content)[1].options[:maximum] %>
  </span>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

sample_app/app/views/shared/_sidebar.html.erb
<strong>Name</strong> <%= @user.name %><br />
<strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
<strong>Microposts</strong> <%= @user.microposts.count %>

sample_app/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

sample_app/app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>